### ISSUE TITLE
Speed issue

### ISSUE THREAD

**Issue by teaglin** [eddieyi/caffe2-pose-estimation#2]
Hi,

I've been trying out your code and the CPU bound computation seems very slow. Especially joint_grouping function takes awhile. I've tried parallelizing it, which provided a solid speedup. But is there anything else that comes to mind to speeding it up?

**Comment by eddieyi** [comment]
Hi @teaglin, thanks for your work on acceleration. The joint grouping should be very quick if implementing it in C++. This might be done in the future.

**Comment by pavithraezhil** [comment]
Hi Taeglin, it would be great if you could share the parallelizing code for joint_grouping.
Thank you.
