### ISSUE TITLE
'utf-8' codec can't decode

### ISSUE THREAD

**Issue by pavithraezhil** [eddieyi/caffe2-pose-estimation#3]
Hello: I'm facing the following error while running infer.py on ubuntu 16.04, CUDA 10, Python 3.5, opencv 3.4. 
Full error in : https://pastebin.com/ax47FAUU

File "/home/pavithra/Downloads/caffe2-pose-estimation/utils/utils.py", line 35, in initialize_gpu_from_weights_file
    src_blobs = pickle.load(f)
  File "/home/pavithra/.virtualenvs/cv/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte

Modifications:
I tried modifying the codec.py file where I changed fileread mode from 'r' to 'rb'. I also changed the errors='strict' to errors='ignore' . Please help me fix this issue. Thank you.

**Comment by pavithraezhil** [comment]
I was able to solve this error. I had to uninstall tensorflow. Then, manually remove all tensorflow files from site-packages and then re-install tensorflow. 

The error was caused due to files from previous versions of tensorflow still remaining. 

I hope this helps.

**Comment by yw155** [comment]
@pavithraezhil , this error should be caused by python 3. I have updated the utils/utils.py for python 3.5. The updated file is here: [https://drive.google.com/file/d/1AxkKnZsK1cxX3BHrdjU6cE7DegKxP-fS/view?usp=sharing](url). You can download it and replace the original one. Thanks.

**Comment by eddieyi** [comment]
@pavithraezhil , this error should be caused by python 3. I have updated the utils/utils.py for python 3.5. The updated file is here: [https://drive.google.com/file/d/1AxkKnZsK1cxX3BHrdjU6cE7DegKxP-fS/view?usp=sharing](url). You can download it and replace the original one. Thanks.
