### ISSUE TITLE
The script hangs right after loading the weights

### ISSUE THREAD

**Issue by pavithraezhil** [eddieyi/caffe2-pose-estimation#4]
The Error: 
(cv2p2) pavithra@pavithra-System-Product-Name:~/Downloads/caffe2-pose-estimation$ python3 infer.py --image-ext /home/pavithra/Pictures/sample.png
WARNING cnn.py:  25: [====DEPRECATE WARNING====]: you are creating an object from CNNModelHelper class which will be deprecated soon. Please use ModelHelper object with brew module. For more information, please refer to caffe2.ai and python/brew.py, python/brew_test.py for more information.
INFO utils.py:  33: Loading weights from: ./models/cmu_coco_iter440000.pkl
Killed
--------------------------------------------------------------------------------------------------------------
System Config:
OS: Ubuntu 16.04
CUDA 10
GPU: 2080 Ti
Python: 3.5
Caffe2 from official repo

I'm unsure as to how to go about solving this? Is it related to CUDA 10? should I change the compute architecture somewhere? Please help me out.

Thank you.

**Comment by eddieyi** [comment]
@pavithraezhil the command should be: python3 infer.py --image-ext jpg
thanks.

**Comment by pavithraezhil** [comment]
Hi, I tried the exact command as above but the script hangs again. 
------------------------------------------------------------------------------------------------------------------
Error:
(cv2p2) pavithra@pavithra-System-Product-Name:~/caffe2-pose-estimation$ python3 infer.py --image-ext jpg
WARNING cnn.py:  25: [====DEPRECATE WARNING====]: you are creating an object from CNNModelHelper class which will be deprecated soon. Please use ModelHelper object with brew module. For more information, please refer to caffe2.ai and python/brew.py, python/brew_test.py for more information.
INFO utils.py:  33: Loading weights from: ./models/cmu_coco_iter440000.pkl
Killed

------------------------------------------------------------------------------------------------------------------------
Please help me out. Thanks.

**Comment by eddieyi** [comment]
Hi @pavithraezhil , there is no any error information, so I cannot determine where the error is occurred.

**Comment by eddieyi** [comment]
@pavithraezhil , the model file is downloaded or not?

**Comment by pavithraezhil** [comment]
Hi,
The model file was downloaded in the correct location but after the statement where the weights are being loaded, the script hangs for 5 min and due to high memory consumption the program gets killed.

I have 2080ti (11 GB).

Thank you.

**Comment by eddieyi** [comment]
@pavithraezhil , I am not sure what problem it is. You can use print function to determine where the error was occurred. Thanks.
